<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Ed Montemayor" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../../../../img/favicon.ico">
    <title>Here is the Blog Post for Project 3</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../../../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../../../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../../../../post/">BLOG</a></li>
        
        <li><a href="../../../../../projects/">PROJECTS</a></li>
        
        <li><a href="../../../../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../../../../post/2020/12/05/here-is-the-blog-post-for-project-3/">Here is the Blog Post for Project 3</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         December 5, 2020 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              
<link href="../../../../../rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="../../../../../rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<p>Howdy,</p>
<p>Here's how Python and R interact.</p>
<pre class="r"><code>#here is a regular R markdown chunk
print(&quot;here we go&quot;)</code></pre>
<pre><code>## [1] &quot;here we go&quot;</code></pre>
<pre class="r"><code>eh &lt;- &quot;ok&quot;</code></pre>
<pre class="r"><code># R CHUNK
names(knitr::knit_engines$get())</code></pre>
<pre><code>##  [1] &quot;awk&quot;         &quot;bash&quot;        &quot;coffee&quot;      &quot;gawk&quot;        &quot;groovy&quot;     
##  [6] &quot;haskell&quot;     &quot;lein&quot;        &quot;mysql&quot;       &quot;node&quot;        &quot;octave&quot;     
## [11] &quot;perl&quot;        &quot;psql&quot;        &quot;Rscript&quot;     &quot;ruby&quot;        &quot;sas&quot;        
## [16] &quot;scala&quot;       &quot;sed&quot;         &quot;sh&quot;          &quot;stata&quot;       &quot;zsh&quot;        
## [21] &quot;highlight&quot;   &quot;Rcpp&quot;        &quot;tikz&quot;        &quot;dot&quot;         &quot;c&quot;          
## [26] &quot;cc&quot;          &quot;fortran&quot;     &quot;fortran95&quot;   &quot;asy&quot;         &quot;cat&quot;        
## [31] &quot;asis&quot;        &quot;stan&quot;        &quot;block&quot;       &quot;block2&quot;      &quot;js&quot;         
## [36] &quot;css&quot;         &quot;sql&quot;         &quot;go&quot;          &quot;python&quot;      &quot;julia&quot;      
## [41] &quot;sass&quot;        &quot;scss&quot;        &quot;theorem&quot;     &quot;lemma&quot;       &quot;corollary&quot;  
## [46] &quot;proposition&quot; &quot;conjecture&quot;  &quot;definition&quot;  &quot;example&quot;     &quot;exercise&quot;   
## [51] &quot;proof&quot;       &quot;remark&quot;      &quot;solution&quot;</code></pre>
<pre class="r"><code>library(reticulate)</code></pre>
<pre class="python"><code>#PYTHON CHUNK
x = &quot;he&quot;
print(r.eh,x)</code></pre>
<pre><code>## ok he</code></pre>
<pre class="r"><code>#R CHUNK
cat(c(eh,py$x))</code></pre>
<pre><code>## ok he</code></pre>
<pre class="python"><code>#python
import numpy as np
matx=np.array([[1,2],[3,4]])</code></pre>
<pre class="r"><code># r
maty&lt;-solve(py$matx)
maty</code></pre>
<pre><code>##      [,1] [,2]
## [1,] -2.0  1.0
## [2,]  1.5 -0.5</code></pre>
<pre class="python"><code>#python
np.dot(matx,r.maty).round()</code></pre>
<pre><code>## array([[ 1.,  0.],
##        [ 0.,  1.]])</code></pre>
<pre class="python"><code>#python examples from HW #10 in a python chunk
import pandas as pd
quakes=pd.read_csv(&quot;https://vincentarelbundock.github.io/Rdatasets/csv/datasets/quakes.csv&quot;,index_col=0)

quakes.shape
#There are 1000 observations of each variable, and there are 5 variables in total.</code></pre>
<pre><code>## (1000, 5)</code></pre>
<pre class="python"><code>np.median(quakes[quakes.long&gt;175].mag)
#the median magnitude for quakes whose longitude is greater than 175. </code></pre>
<pre><code>## 4.5</code></pre>
<pre class="python"><code>np.median(quakes.depth)</code></pre>
<pre><code>## 247.0</code></pre>
<pre class="python"><code>np.std(quakes[quakes.depth&gt;247].lat,ddof=1)</code></pre>
<pre><code>## 3.577252109778374</code></pre>
<pre class="python"><code>np.std(quakes[quakes.depth&lt;247].lat,ddof=1)</code></pre>
<pre><code>## 6.1500996392534564</code></pre>
<p>The standard deviation of the variable lat when depth is greater than the median depth is 3.577252 and the standard deviation of the variable lat when depth is less than the median depth is 6.1501. This suggests that earthquakes at lower depths vary much more in latitudinal coordinates.</p>
<div id="heres-a-pic-of-a-wooden-van-i-decked-out-in-forza" class="section level3">
<h3>Here's a pic of a wooden van I decked out in Forza:</h3>
<div class="figure">
<img src="../../../../../post/2020-12-05-here-is-the-blog-post-for-project-3_files/IMG_3382.JPG" width="300" height="300" />

</div>
<p><a href="https://open.spotify.com/user/edg.rdo?si=jjJzWjTRRp-DmDehf5KItA">Follow my Spotify</a></p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../../../../js/docs.min.js"></script>
<script src="../../../../../js/main.js"></script>

<script src="../../../../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
